### ISSUE TITLE
Ace 3.3.2 Leg Damage "ace_medical_healHitPointAfterAdvBandage" not working

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#10]
https://github.com/acemod/ACE3/issues/2389

**Comment by adios113** [comment]
The Broken Leg thing is a feature. The way it works is that you can only "fix" your Broken Leg with PAK.
This can be changed though config by "ace_medical_healHitPointAfterAdvBandage" config setting to make it heal with bandage, which is apparently not working. Awaiting a fix from ACE team, probably on 3.4.0

**Comment by Fourjays** [comment]
Might be worth verifying both the extent of our issue or what exactly the ACE team are fixing. The referenced issue is unclear and it sounds like this setting only doesn't work when legs are bruised.

**Comment by adios113** [comment]
this is what is causing the broken legs not to be healed.
https://github.com/acemod/ACE3/issues/2498

**Comment by adios113** [comment]
fixed by me. Needs testing on the server. Fix available on the test repo.

**Comment by adios113** [comment]
Fix has been tested on the server. Broken Leg bug dissapearing, everything seemed to work properly, but then we discovered, that the reopening of the wounds is not working properly - wounds do not reopen at all, if a wrong bandage is being used. In my opinion it is still better to sacrifice the wound reopening in favor of the broken legs, since it has a bigger impact on our gameplay. True, that the Corpsman will be less useful because of that, but I think its worth. Additionaly I think that when ACE 3.4.0 will be released, it will work the same as with the fix, cause the version of the file we used to fix the broken leg bug is the one which is supposed to be included in 3.4.0. I'll make a post on ace github, informing them of this bug, so for now I think that every outcome is possible.

**Comment by adios113** [comment]
Reported on Ace's github. https://github.com/acemod/ACE3/issues/2878

**Comment by adios113** [comment]
Fixed in https://github.com/acemod/ACE3/commit/6031eb8c6e6f1a3efdf761a18dc08912753af736

**Comment by Fourjays** [comment]
This is now pending the imminent release of ACE 3.4.0 and a possible fix.

**Comment by ShiFoo** [comment]
Ace3 Milestone 3.4.0 has closed all issues! We should expect the release soon!
https://github.com/acemod/ACE3/milestones

**Comment by ShiFoo** [comment]
Its out!!!!
https://github.com/acemod/ACE3/releases

**Comment by ShiFoo** [comment]
Fixed with 3.4.1
