### ISSUE TITLE
Server-side testing of ASR, MCC and ALiVE

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#232]
Need to perform server-side testing of MCC and ALiVE to check for any issues. Particular attention should be paid to the following:
 - Ability to handle realistic numbers of units for an op.
 - Ability to function with and utilise the headless clients.
 - Server and client-side performance during an op-like scenario.
 - Compatibility with existing Zeus/Ares functionality.
 - Stability of MCC. Was previously removed due to reports of it causing server crashes.
 - Practicality of ASR. Was previously removed due to AI refusal to respond to new orders and desire to engage at long distances.

**Comment by Fourjays** [comment]
I will setup a test instance in the next few days.

**Comment by TheGrandVizier** [comment]
ALIVE: http://www.armaholic.com/page.php?id=23684
MCC: http://www.armaholic.com/page.php?id=19580
ASR AI: http://www.armaholic.com/page.php?id=24080

**Comment by TheGrandVizier** [comment]
All 3 Uploaded to repo

**Comment by ShiFoo** [comment]
For the server instance, make sure that you also include the RHS addon. D/L link is in the Armaholic thread below the videos: http://www.armaholic.com/page.php?id=24080&highlight=ASR%2BAI%2BRHS

**Comment by Fourjays** [comment]
Will need to be there for all. AI isn't always on the server only.

**Comment by Fourjays** [comment]
Everything is available on test repository. Beware "@TSTS" folders are for the server only.

**Comment by Fourjays** [comment]
My early tests have turned up a number of issues:
 - CTDs when spawning 2-3 units via Zeus.
 - Noticable lag when spawning objects and units via Zeus.
 - Slow loading times (from menu to map, map to menu) even with lightweight maps.
 - Errors clientside unless filePatching is enabled (expected, practicality?).

**Comment by TheGrandVizier** [comment]
Should I test all of them together or would there be value in testing separately from the get go?

**Comment by Fourjays** [comment]
Looks like the CTDs are caused by Leights Opfor Pack. In Zeus I spawned 6 squads for BLUFOR and OPFOR, then spawned IND in the middle. No crash unless those IND units were from Leights Opfor Pack.

Slow loading times are likely caused by MCC or ASR_AI. There is quite a significant time increase for each load going from menu, to editor, to game, to editor, and then back to menu. Only occurs when BWI_Misc is loaded.

**Comment by ShiFoo** [comment]
I tested your scenario locally and i was not able to reproduce the CTD. On which map did you test it? Would be a real pain if this was an occasional issue!
I also cannot confirm that spawning objects and units through Zeus causes lags. For me, there was no difference.
The loading times are increased, though. I saw that MCC or ALiVE are playing some kind of video clip in the menu where soldiers are mounting in two ghosthawks and are taking off. Maybe this kind of "extra load" causes the increased loading times. I also tried to launch the game with default empty world but i guess it only has an effect when the game is started the first time. When you leave the editor or LAN game, it gets loaded...

Filepatching must be enabled for ASR. Can you confirm that filepatching was enabled when you experienced the lag when placing down units? ASR (local) + zeus placed unit (local)...

**Comment by Fourjays** [comment]
The CTD is tested in a basic Zeus setup on Virtual Reality. I'm able to reproduce it pretty consistently. If I use non-Leights groups nothing happens, but as soon as I try it with Leights units it will CTD on the third or fourth group spawned. It appears to be a video memory leak from the error log (and Leights has many errors relating to textures so theres correlation).

On further testing the Zeus lag appeared to occur in our existing modpack setup as well and not be related to the AI mods specifically. If you compare to a vanilla setup, there is a noticeable 1 second delay to all unit spawns.

Regards the slow loading times, it definitely doesn't occur with ALiVE. It is specifically when the BWI_Misc set is enabled, which is where ASR and MCC are located. I don't think it is connected to the video clips as it is on every load, and I'm getting the default menu scenes too.

Filepatching is enabled through all of this. The immediate problem with ASR is that if anyone loads up the game without filepatching and doesn't connect to the server, they'll get frequent error messages from ASR (including on exiting to the main menu post-mission). Zeus' will likely need it enabled locally too if AI is running locally. So it seems like everyone will end up needing to enable it.

**Comment by ShiFoo** [comment]
I am just curious what happened to LOP between now and, for example, the last milestone. Ok it is throwing a lot of errors in the log but as far as i know it did not severly crash anything (except for Cavacs mission) or at least the crash was not consistently reproducable, was it? 

Oh you mean "this" lag. Ok, this has been there for as long as i am in BW. I only have it significantly if i spawn squads.

Mhh, ok. God knows what the mods are initializing and deinitializing between sessions...

I would also agree that everyone must have file patching enabled. If players manage their profiles through Arma 3 Sync (like everyone should), then filepatching can be activated for the BW profile and will not effect others. Its fine, imho.

**Comment by Fourjays** [comment]
We've never looked closely at what caused a lot of problems and crashes.

Back to the AI testing, only the menu delay appears to be directly connected.

There'll need to be a meeting discussion about enabling filepatching.

**Comment by abelarno** [comment]
During testing, when all of MCC's logistics and medical stuff was turned off, I still got the MCC dialog option when trying to interact with ACE. Not sure how much this happens. It happened once to me during a 20 minute test.

**Comment by LordCavac** [comment]
Every time I start the game and load a map I get the following error: "Script \userconfig\asr_ai3\asr_ai3_settings.sqf not found" I have run the batch file to copy to user config, but have not manually moved them yet, however, when I navigate to the folder it is there. When I click close on a map it goes back to loading screen and loads the map a second time. Since I didn't see this anywhere else I assume it is only happening to me.

Testing with zues I have noticed that if ALIVE attempts to place helicopters in a hangar they have a tendency to explode(happened every time I checked but it may have just been that particular kind of hangar, I was using takistan). I would bet this is due to the units being spawned slightly above the ground when being moved from simulated to placed causing a collision with something inside the hangar.

If you attempt to remote control an ALIVE placed unit in zeus it will remove your control after a second or two and place you back in zues with your camera on the edge of the map. 

If you manually place a unit in zues and control it ALIVE does not recognize it as a player and will despawn the nearby AI if the zues player is not located within spawn distance. UAVs seem to be iffy with this issue, I could see some enemies, but not others when looking at where I know they were located time constraints prevented me from testing this further for now, but it should be looked into. I was within 20m of the AI.

Interesting note: If the AIs are not spawned but are shooting at you you can still hear the bullets/explosions and take damage. I verified this with the manually placed unit control trick.

**Comment by abelarno** [comment]
>Every time I start the game and load a map I get the following error: "Script \userconfig\asr_ai3\asr_ai3_settings.sqf not found" 

Turn on file patching in your launcher, that fixes it.

**Comment by ShiFoo** [comment]
>Testing with zues I have noticed that if ALIVE attempts to place helicopters in a hangar they have a tendency to explode(happened every time I checked but it may have just been that particular kind of hangar, I was using takistan). I would bet this is due to the units being spawned slightly above the ground when being moved from simulated to placed causing a collision with something inside the hangar.

I guess this is something we have to live with. We all know how unforgiving the ArmA engine is when it comes to collision while placing stuff. We also had it yesterday where a random BTR exploded because of its placing. 

>If you attempt to remote control an ALIVE placed unit in zeus it will remove your control after a second or two and place you back in zues with your camera on the edge of the map.

This could be a thing with the ownership but not entirely sure. Sounds like an ALiVe and not an ASR issue. Because of your file patching setting, i assume that your ASR was not properly initialized. @abelarno i want to know if this is also an issue on the dedicated server. 

>If you manually place a unit in zues and control it ALIVE does not recognize it as a player and will despawn the nearby AI if the zues player is not located within spawn distance.

That is part of the caching and "as intended". It should reappear though when a player comes close again (depending on the settings).

>UAVs seem to be iffy with this issue, I could see some enemies, but not others when looking at where I know they were located time constraints prevented me from testing this further for now, but it should be looked into. I was within 20m of the AI.

Correlates with my prior statement. The caching is a function to save resources. Seems like an UAV does not trigger the spawn. This could mean that the AI spawn radius must be equal or greater than the operating distance of the UAV. Minor thing but we will keep it in mind.

>Interesting note: If the AIs are not spawned but are shooting at you you can still hear the bullets/explosions and take damage. I verified this with the manually placed unit control trick.

This is also a matter of AI spawn radius. Seems like yours is too small.

In general: we are still trying to balance good settings for ALiVE and MCC. While we tested some ALiVE, i want to shift the focus to MCC for tomorrow and the day after, if nothing extremely critical arises with ALiVE. @LordCavac could you maybe test some MCC missions? Just load one of our templates and start using MCC without any further preparations. This should work from scratch!

**Comment by LordCavac** [comment]
My spawn setting was at 1.5km, the documentation says to not set it above 3km or it can cause framerate issues if I remember right.

I'll check out MCC tomorrow when I get back from work.

**Comment by adios113** [comment]
> Interesting note: If the AIs are not spawned but are shooting at you you can still hear the >bullets/explosions and take damage. I verified this with the manually placed unit control trick.

Units in ALiVE are supposed to spawn while player is progressing, not with the ingerention from zeus and a spontaniously spawned unit in the middle of the concentration - takes time to load, they would probably appear with time.

Units spawning is dependent on three types of units:
 * Infantry (1500)
 * Helicopter (1500)
 * Airplane (0)
And by radius determined inside the AI Manager Module - default numbers in brackets.
As you can see Airplanes do not trigger any unit spawns by default - explains why the UAV didnt.

Aight. Let's go to my review of ALiVE after I did some testing.

Overall performance is very satisfactionary. Abel's template provided us with over 400 AI GROUPS (not single units). Gameplay was stabile, Framerate both client and serverside was without any complains. Of course, we will discover how really ALiVE handles everything live, with other players. 

Alive has big amount of features and comes with very useful documentation, providing information on every single feature ALiVE has to throw at us. 

I experienced two server crashes while playing on the server with ALiVE. Both happened shortly after I logged in into MCC. I'd like to take a look, at the server log, to find the cause of this.

MCC results to follow later

**Comment by ShiFoo** [comment]
>I'd like to take a look, at the server log, to find the cause of this.
FJ c/pasted the logfile after crash/desync. It did not show any valuable information. I agree that MCC is a potential suspect. This is why i want more testing on it. Regarding the warroom and the DB: As i explained yesterday, we are currently at "Step One" ( stability and performance testing ). I would like to take some more time on this and then switch over to MCC. The Warroom and DB are "interesting features" but are not vital for the question whether the addons gets in or not. This is why i want to postpone testing of those features (for now). Lets take it step by step and not rush things. Otherwise critical details can be overlooked.I will do some final testing with ALiVE. Abel, Cavac and aDi: if you are fine with ALiVE (and have nothing more to add to "Step One"),  you can switch over to MCC which gives me extensively more headache. I will have last looks at ALiVE myself today.

**Comment by abelarno** [comment]
>This seems odd. So if a plane flies over an AO or should patrol a sector outside of friendly groundforces sight, it will not trigger the spawn of hostile armor even though it is there? This doesnt seem very reasonable... Please confirm that with the ALiVE wiki!

This is a setting in ALiVE. Spawn radius is at default on 0, because planes flying over land at a high speed will trigger a lot of AI spawning, without anybody actually seeing them. This will result in unnecessary lag. When we have people on the ground, the UAV should be able to see AI within 1.5km radius of them.

**Comment by CervenBWI** [comment]
Spent some significant time on the server last night, specifically testing MCC features that will likely be used by creators in ops. During my little over an hour testing, I didn't experience any crashes.

- Paradrop functionality and Pod Drop functionality work as advertised. Huge improvement over current systems of entry on that front. One particular issue I faced is that the helicopter in both instances doesn't like to depart the area after the drop, and simply wants to hover in place. Issuing orders to the aircraft seemed to have mixed results. 

- Convoy functionality seems pretty meh. It involves setting up the vehicles for the convoy, plotting waypoints, and then starting it. In my two attempts, I had significant difficulties even getting them spawned. I'd like to spend more time with this to ensure it isn't operator error.

- One pretty crucial bug involves death. Now with MCC, if you are controlling a unit through Zeus Remote Control ( NOT hijacking, this is a different feature entirely ), and your actual character dies ( i.e the actual Zeus ), you will respawn, become paralyzed, and the only way to fix the issue is to leave the server and rejoin. No amount of respawns, arrest/frees, or anything else will fix this issue. All other characters you remote control will be controlled by the AI, and you'll just be along for the ride. This bug has been there for as long as I can remember - it's pretty easily avoided, since Zeuses very rarely die.

- Mission Creation System is quite good. Useful for creating a populated AO. 

- GAIA seems to work relatively well, though I think ASR does the job just fine. I utilized GAIA for an attacking force against an entrenched enemy not controlled by GAIA, and ASR utilized cover and flanking to reasonable effect. I'm also noticing a significant increase in suppression fire.

- Brushes work fine. Very useful for a variety of purposes.

- Zoning System seems to work great as well.

- The "Ambient Battlefield" option didn't seem to work right, but it's a new feature to me. I may have been using it incorrectly.



Ultimately, it's what I expected. MCC is a very powerful tool that has some issues. Frankly, it's going to be a little trial and error with Zeuses learning what tools to use and which to avoid, but I think it's a pretty good bag of tricks to give people to utilize.

**Comment by CervenBWI** [comment]
Oh, one quick note - with the 'Hijack' feature in MCC, you BECOME this unit. As in, this becomes your respawned character upon death, and an AI will assume control of your 'main' character. Keep this in mind when controlling units.

**Comment by TheGrandVizier** [comment]
Also keep in midn that MCC allows ZEUS to whoever is logged into it, regardless if he is in a zeus slot. It's like it has it's own zeus slot that is not occupyable otherwise.

**Comment by ShiFoo** [comment]
Ok, maybe the desync that aDi and i were experiencing last night resulted from using an ALiVE template but also using some MCC functionality (at minimum: just logged in). As far as i can recall, Abels ALiVE template had some MCC modules which disabled most of its features and it worked just fine. It should cope with eachother but, in my opinion, never be really used in conjunction. As long as we get ALiVE and MCC stable seperately, i am more or less satisfied.

Also another "Feature" of MCC is: When you are Zeus and you enable ghosting (through MCC) and hijack a unit, this unit becomes civilian (or anything similar), starts shooting enemies while enemies cannot/will not shoot back...

**Comment by adios113** [comment]
MCC Modules:

* Add Objects/Units to Zeus 
> Doesn't work at all.

* Ambient Civilians.
> Works as intended. Can't unspawn them. Upon deletion they respawn.

* Ambient Civilians (Restrict)
> Doesnt prevent the Civilians from spawning in the selected area. - Not working

* Armed Civilians
> Doesnt equip the selected civilian with weapons."error: No unit selected" - Not working

*Atmosphere
> Works as intended. The Blizzard's Wind sound wont stop when you clear the Atmosphere until the SFX sound reaches to the end.

* Capture Zone
> Details to follow, as it is a part of the "RTS" system from MCC.

* CAS
> Doesn't work - no planes to select.

* Damage Part
>Doesn't work - "No unit selected"

* Door Lock/Unlock
> Doesn't work. Spawned couple of open vehicles, spawned the module with max radius - vehicles still open. Unlock doesn't work, Random Lock doesn't work.

* Evac Vehicle
> Doesnt work - "No vehicle selected"

* Garrison
> Works as intended. Be subtle with the radius and density or it will spawn too much/too dense.

* IED/Suicide Bomber
> Doesn't work. "No object selected". Should work both on units and objects.

* Night Effects.
> Works. Destroys lamps in the area, removes night vision from all units (even from players if selected). Forces flashlights on AI.

*Start Campaign
> Works as intended. Has some nice cosmetical features, like voice over during the briefing.

*Undercover Agents
> I remember that it worked for me in singleplayer, but seems not to work in Multiplayer. It's supposed to change the faction of the selected unit to Civilian and remove the weapon of the selected unit on tick. Error: "No vehicle selected". I suspect no MP compatibility on the other modules producing the same errors.

* War Zone
>Works as intended. Be aware - can level the whole map and kill you if you're in the area.

* Vehicle Kiosk (works)
* Set Resources (works)
* Capture Zone (doesnt work)
> Are all part of the MCC's Supplies/Logistic system.

To summarize the MCC's Zeus Modules:

Most of them do not work, alltough I tested them earlier in Singleplayer where the percentage of not working modules was much smaller. Some of the modules are very nice like the Atmosphere, Night Zone (I will port them into my Addon, if MCC wont go in.) and some of them are already covered by other mod's (Ares, Ace) and are being executed in a better, more stabile fashion. Rest didn't work for me on the Server only or at all (IED/Suicide Bomber being the example of a module not working at all, Armed Civilian being the example of the one working in SP, but not on the server.).

Finalizing, most of the stuff does'nt work. Looks like MCC's quality is still niche , compared to other Zeus mods. Has some nice features, but its nothing we can't do ourselves.

MCC Main Window:

* Spawn Units/Group
> Doesn't work while spawning the Group/Unit on map click. Does work while spawning the Group/Unit inside a zone.

* Supply Drop
> Works. Type of drop and type of transport used to perform the action depends on the action. Kinda OP. You can drop unlimited (?) amount of vehicles with 1 drop. http://steamcommunity.com/sharedfiles/filedetails/?id=604162805

*CAS
> Works. Depends on selected faction. Available Ordnance is not vehicle dependand. (You can drop JDAM with a chopper).

* Artillery
> Works. Addition to the Zeus' ordnance module. Has some more weapons to choose from and has a beautiful sound effect added from CoD 2 which is the climatic whistle while a round is about to hit the area.

* EVAC
>Works Partialy. Available EVAC vehicles depend on selected faction. Vehicle spawns, but I can't figure out how to make it proceed with the evac. Either I'm doing something wrong, or it's not working.

* IED
> Works. MCC keybinds need to be adjusted, to allow disarm action.

* Convoy
> Doesn't seem to spawn the Convoy after placing the Waypoints. 

* AC-130
> Says, that the Plane has been spawned, but it didnt.

* Brushes
> Works as intended.

* Enable Roles
> Requires @iniDB, which we are not runing. (Database extension)

* Zeus
> Works as intended.

* Arsenal
>Works as intended.

* Weather
> Provides additional options to change, but most of the stuff doesn't work - known locality issue in the weather, plus I already have a working weather module in my Addon. Without any of those issues.

* Start Locations: 
>Works as intended. CAUTION: May replace your current gear to the one you should have as default (Editor unit class - custom loadout won't load in.)

* Briefing
> Seems not to update the "Briefing" Section after submiting the text.

* Tasks
> Works as intended. The one from ZEUS from Bohemia is a lot easier to use though.

* Triggers.
> Works, though it's hard to use.  If you don't have any knowledge about Triggers - do not use it.

* Zones, GAIA, Logistic, Fortifications

> OKAY. Here comes the hard part. I started with some zones. Created two and tried to populate them http://steamcommunity.com/sharedfiles/filedetails/?id=604162931 with selected factions. (MAKE SURE TO hold and drag on zone creation, to specify the area, or there wont be any place for units to spawn.) I left both zones under control of GAIA, provoked a skirmish and left them for a while, doing some other testing. Server/HC FPS was at stable 48. Worse with client FPS, but only if you were in the middle of the fighting (5FPS-20 - for my PC it is a very significant drop). Estimate amount of units  in both zones was around 150-200, so when i teleported myself into the middle, the FPS drop was significant, so it's preferable to not do such things live. The size of the MCC Zone is relevant to the amount of the units which will spawn if you choose to "Ocuppy" the zone with the selected faction. Ex. Zone 5 (http://steamcommunity.com/sharedfiles/filedetails/?id=604162980) and Zone 6 (http://steamcommunity.com/sharedfiles/filedetails/?id=604163010), so watch out for the zone size. So, performance wise, MCC can handle big amount of units - even more if you decide to cache them, but you need to be carefull about the amount of units actively taking part of the battle, which affects client FPS - It was always an issue, and there's really nothing we can do, except the sponsorship of a military class computers for every single BWI member and buying Bohemia's Studio to force them to work on performance.  Final Performance test: http://steamcommunity.com/sharedfiles/filedetails/?id=604163044. Which was kinda weird, that the HC was runing on 48 FPS. So I checked and this happend : http://steamcommunity.com/sharedfiles/filedetails/?id=604163126. Not a single unit was being transfered to the HC. Raises some question and explains why the HC FPS was untouched, while I previously believed, that it's just doing such a great job. I finished my testing in a rather questionable way: http://imgur.com/lfg52pq

* Summarizing MCC overall:

> My test took around 4 hours. Experienced some minor desyncs while MCC was being used, but in my opinion if the old bug with zeus and the big desync is still here, we won't find it out until it's live. I'm concerned if even most of the features work properly and to be honest I am very sceptic, alltough I hoped, MCC's quality has been improved a lot since the last time we used it and reffering to our latest standards in terms of mod quality - MCC does not meet them.

**Comment by adios113** [comment]
Whole TEST session was performed on the BWI Test Server.

**Comment by TheGrandVizier** [comment]
Dusty reports suicide bombers work for him fine. Perhaps a case of
incorrect usage?

**Comment by adios113** [comment]
Worked for me fine as well, but only in Singleplayer.

**Comment by LordCavac** [comment]
With the UAV issue I was using a growler, and my spawn distances were set to default, I intentionally drove the UAV farther than that away from my position to see what would happen. 

With the controlling a zeus placed AI I did wait for a more than reasonable amount of time (several minutes) and nothing ever popped up but I was getting shot at so I know they were around.

**Comment by TheGrandVizier** [comment]
A historic thruth has been that MCC and zeus dont jive well. the same can be assumed for Zeus and ALIVE. If you are testing a combination of features from 2 mods, the base assumption should always be "no, its not gonna work".

**Comment by Fourjays** [comment]
MCC has been removed from the test setup and will not be included in the update.

**Comment by Fourjays** [comment]
I've created inclusion/deployment issues for both ALiVE (#247) and ASR AI (#248).

**Comment by Fourjays** [comment]
Testing has been concluded.
