### ISSUE TITLE
Incorrect frequencies listed on CommCard

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#252]
The new CommCard contains incorrect frequencies and structure. The Assistant Platoon Leader, Medical and Logstics personnel are all to share a single shortwave frequency of 101, with additional set to 105.

The Assistant Platoon Leader should also be equipped with a backpack radio if they aren't already,  for direct Squad to Assistant Platoon Leader communications.

**Comment by ShiFoo** [comment]
The Assistant Platoon Leader currently only exists "virtually" (there is no loadout file and thus no Armory entry) because his loadout doesnt really differ from the PL. Assistant Platoon leaders should use the Armory slot of the PL until we decide that he should have different gear.

I will update the CommCard now.

**Comment by ShiFoo** [comment]
Changes committed to develop. Closing.
