### ISSUE TITLE
Replace full Arsenal with a whitelisted Arsenal

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/blackwatchint#263]
Want to set up the Arsenal with a whitelist for permitted customizations only. Options should probably include:
 - Beards, moustaches
 - Shemaghs
 - Glasses
 - Camopaint
 - Scopes (if possible)

**Comment by TheGrandVizier** [comment]
Allowed alternate guns?
Earplugs (Ace stuff in general? Sandbags, bodybags, etc?)

**Comment by Fourjays** [comment]
Alternate guns only works if they can be limited by role/loadout. Not sure if the whitelist script allows that level of tuning.

I would like to have a smaller test version made first so we can verify that the whitelisted arsenal functions as desired, before we start building the full whitelist.

Also found this (https://m.reddit.com/r/armadev/comments/3aqe6v/display_classnames_in_virtual_arsenal/), which may be helpful in getting the classnames. May need altering to display items too though.

**Comment by ShiFoo** [comment]
I think it might be easier to try to dump classnames + display names of the items/weapons from CfgWeapons.

I dont know if it is good. The first google result:
https://forums.bistudio.com/topic/117767-infantry-weapons-retrieved-from-config/

**Comment by Fourjays** [comment]
This may be a no go. Did a test this evening, and it appears a whitelist does not prevent increases to gear already on a person (i.e. if frag grenades aren't whitelisted and a loadout has frag grenades, you can take more frag grenades). I tried a mod that could have solved this, but it resulted in any non-whitelisted gear getting removed entirely.

An alternative but imperfect option may be a regular inventory box of permitted items.

**Comment by TheGrandVizier** [comment]
^ then we would need permitted item per faction set, correct?
Do "permitted items" include helmet variation within same camo scheme?

**Comment by ShiFoo** [comment]
I think the main concern is about items that can be stored in your backpack/vest/uniform like ammo or medical supplies.
This would mean that all weapons, vests and backpacks are allowed. Maybe even scopes because we see when someone is picking a magnified one. Maybe another approach is to write a script for the APL/PL which queries the content of backpack/vest of each player and compares it to default quantities or simple presence (e.g. rifleman has cTab device / GPS ). Also, i could give APL/PL the ability to remove arsenal from the spawn ammo box.

**Comment by TheGrandVizier** [comment]
> This would mean that all weapons, vests and backpacks are allowed.
Within the existing loadout sets, i assume? 
Or do you mean, all vests / backpacks / uniforms available in arsenal?

Regarding numeric regulation, can this be done as they TP into the AO? (since the TP is now static)

**Comment by ShiFoo** [comment]
All uniforms, vests, backpacks in the arsenal. There is no need to regulate them, imho.
Well, i dont know yet. That is of course a lot of scripting effort... certain classes need certain ammo (rifleman != AR) or medical supplies (CFR != CM != Rifleman). I am not really happy with both solutions because they seem impractical. I am just brainstorming...

**Comment by Fourjays** [comment]
If we were happy with allowing helmet/uniform variations we wouldn't be removing the arsenal. There are two goals:

1. Stop time wasted "dressing up".
2. Stop people taking unauthorized equipment.

I think helmet and uniform variations should be handled by loadout randomization, as we did with the PMC loadouts. Allowing free choice on this defeats the first goal.

Unauthorized equipment can be partially solved by an Arsenal whitelist. The whitelist can only stop you taking gear that isn't in the list and isn't on your person. If the quantities of certain item types (9x mags, 4x smokes, etc) can be checked pre-insertion, then the whitelist is sufficient. If not, then while an inventory box containing the permitted variations (mostly facewear, scopes and a few ACE items) isn't the perfect solution, it is the best for now.

**Comment by Fourjays** [comment]
As per recent discussions, the arsenal will be replaced with normal inventory boxes of allowed customizations.

These boxes have been created as part of #269, closing this issue.
