### ISSUE TITLE
Hint, Scenario End modules stop working at some point along the mission.

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/blackwatchint#30]
At some point during a mission, zeus loses ability to use the Hint and Scenario End modules.
They both become submitted before the user is able to provide input or select anything within the dialogue.

Unable to reproduce on demand but this is consistent and happens to 90% of the time fairly early on.

**Comment by ShiFoo** [comment]
Maybe Ares interfers with the Zeus menu in some kind of point. Can't really see how we can fix this ourselves. For the mission ending bug i could imagine adding an Action to the Arsenal ( for Zeus slots only ) to either end a mission with success or failure. I will investigate this evening.

**Comment by TheGrandVizier** [comment]
I would love it if we could pin point who is at fault (which mod, or perhaps even bohemia, if thats the case).

It is not unreasonable to assume a specific mod may be fucking this as we have seen similar shit happen before.

**Comment by ShiFoo** [comment]
If there is a bug report on official Arma 3 bug tracker, then its bohemia. If this problem was not present before the mod pack update, its a mod ( most likely one of the mods that were updated ). That is what we can try to investigate. But even if it is a mod that was updated we cannot reproduce it because we dont know what triggers this behaviour ( if that is even defineable ). Maybe there is more information on the several mod pack sites. Maybe someone else have the same problem

**Comment by TheGrandVizier** [comment]
I think I am more inclined to isolating which mod causes this.
While the HINT is for sure a bohemia issue and has an issue on the bohemia tracker, the rest of the behavior is not reported anywhere.
This causes me to think it's some sort of combination of things we use.
Also, the HINT works at first and stops working at some point, but Scenario flow does not work from the get go, I believe.

My goal for this evening is to isolate which mod creates this issue. I will report my findings when there are any.
The The best test to confirm the bug is occurring is trying to use scenario flow once you are in the mission. The spcific trriger is irrelevant if we can rule out mods or create an environment in which it does not occur.

**Comment by Fourjays** [comment]
Both hint and scenario flow work from the start, but they fail at an undetermined point in the mission. Hint can be checked regularly during a mission, but Scenario Flow can't because if the bug has triggered it will immediately end the mission. Other modules may also be affected (not tested).

There is an issue for Hint on the Arma 3 issue tracker (http://feedback.arma3.com/view.php?id=26291), but as described it is not the same as our issue (for us it works fine at mission start and no error is ever displayed).

This issue predates modpack revamp, but probably not the Q3.

**Comment by ShiFoo** [comment]
For testing, please keep in mind what i said in my earlier post:
> launch Arma 3 with "Show script errors" and play around with Zeus.
> Maybe we are lucky and a problem is beeing reported by the engine.

**Comment by Fourjays** [comment]
During flight school today I ran with "Show script errors" enabled. Apart from an error on launch (something about HLC AKs), I saw no errors displayed in-game. Both Hint and Scenario Flow had failed by the end of the session.

**Comment by adios113** [comment]
I'll work o a work around until its fixed, by adding an action menu action to zeus slot, to end the mission,

**Comment by TheGrandVizier** [comment]
Only happens in multiplayer.

**Comment by ShiFoo** [comment]
There will be a workaround where all zeus slots have additional actions on the VAS at the spawn. This will include ending mission (success and failure) and my Reclaiming AI Ownership script from the forums

Cross post from https://github.com/adios113/blackwatchint/issues/29
>Zeus slots have addition actions on the SpawnVAS:
>-- End Mission (Success)
>-- End Mission (Failure)
>-- Implemented "Reclaim AI Ownership" script as action on the VAS for convenience
>
>To keep this actions hidden from normal slots and to handle correct removal of those action again >when reslotting between Zeus and normal, the script onPlayerRespawn.sqf handles these actions.

**Comment by adios113** [comment]
Already implemented on the server.

**Comment by Fourjays** [comment]
This will remain open until we can determine the exact cause and full extent of the issue.

**Comment by Fourjays** [comment]
The issues discussed do not seem to have resurfaced since the move to Arma 3 v1.54. Will close as fixed for now.
