### ISSUE TITLE
Al-Jak Map.

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#44]
**Description:** Al Jak is a fictional terrain located somewhere in middle-east.

I decided to create this map to test the real power of Map Builder, infact the heightmap has been created with L3DT, sat map and mask with PhotoShop and the objects have been placed with Map Builder.

Thanks to this mod Al Jak has been created in less than 2 weeks, I have to thank Jona that helped me to place some objects in Multiplayer mode ( yes you can with MB and it's awesome).

**Download:** http://www.armaholic.com/page.php?id=29546
**Size:** 39MB

**Comment by wingatex** [comment]
Map is small only good for one time op and all you can see is the edge of the map

**Comment by karlkarl93** [comment]
This is a very tiny map. It consists on a single town. The town itself was very well made and it would be great for CQB combat but it's not very reusable and probably cannot be used for most ops.

**Comment by Fourjays** [comment]
Very small map, but well made. Due to its size I'm not sure how much use it'd actually get. It appears to be technically sound with no obvious issues.

http://steamcommunity.com/sharedfiles/filedetails/?id=565038904
http://steamcommunity.com/sharedfiles/filedetails/?id=565039068
http://steamcommunity.com/sharedfiles/filedetails/?id=565038983
http://steamcommunity.com/sharedfiles/filedetails/?id=565039245

**Comment by Fourjays** [comment]
Accepted in the meeting on 29/11/15.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Built into the test repository, tested and pushed to live.
