### ISSUE TITLE
SFP: Islands

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#45]
**Description:** 
Swedish Forces Pack will no longer come with islands, we will release them separably due mostly to big file size and not as often updated as the rest of the pack.

For now we are working on three islands, Sturkö, Rosö and Wamako.

Wamako was if not the first at least one of the first islands for ArmA3. It was originally meant only for internally figure out how to work with arma3. It will come with some updates in the future.

Rosö will be our main island, we will make new objects, buildings and features. The island have been designed "from scratch" based on different areas in Sweden its not an accurate copy of any place but instead features both military bases, airport, military runways, harbours, a good road network. What we have in mind is making an island that offer many mission possibilities. Also includes a minor island in one corner in order to have a base to "launch that invasion" from. I really enjoyed that part on Everon.

Sturkö, this is an island known for some since we had it in ArmA2. Its based on real world data.
Mostly known for the events in which a Soviet submarine was discovered to have run aground, just a few miles outside a Swedish naval base.

**Download:** http://www.armaholic.com/page.php?id=25143
**Size:** 700MB

**Comment by ShiFoo** [comment]
I had a look at this mappack.
I was only able to load Wamako and Sturkö. Rosö wasn't listed in the editor map selection.

First i spawned on Sturkö. The initial impression was pretty good, because i spawned inside the woods and it felt like a northern-europe setting. But after browsing around in Zeus, i have spotted some very ugly spots. Especially the towns and cities were quite disappointing. Looked like random house placement:
http://steamcommunity.com/sharedfiles/filedetails/?id=548684977

There were also some ugly terrain formations:
http://steamcommunity.com/sharedfiles/filedetails/?id=548685026

The airport doesn't look too good either:
http://steamcommunity.com/sharedfiles/filedetails/?id=548685067

Second island was Wamako:
Again, spawn impression was nice. I liked the colours:
http://steamcommunity.com/sharedfiles/filedetails/?id=548685323

But then again:
http://steamcommunity.com/sharedfiles/filedetails/?id=548685151
http://steamcommunity.com/sharedfiles/filedetails/?id=548685111

The main capitol was quite ok tho:
http://steamcommunity.com/sharedfiles/filedetails/?id=548694629
http://steamcommunity.com/sharedfiles/filedetails/?id=548694660

But between the cities is just bleak landscape. Barely woods, 90% open field with a couple of bushes and trees. It just doesn't open up any tactical opportunities.

Wamako is better than Sturkö, but, in my opinion, that doesn't suffice

**Comment by wingatex** [comment]
Map is a lot of wilderness with houses in it. It works with our modset without issue but the map its self is very buggy in my opinion. The main problem is while their are a few arma 2 building a lot look made by them but haven't really finished off the texturing and things like doors on the buildings don't work. For the size of the mod and with everything else we currently have I don't feel it is worth having.

http://steamcommunity.com/sharedfiles/filedetails/?id=5682567
http://steamcommunity.com/sharedfiles/filedetails/?id=568256860
http://steamcommunity.com/sharedfiles/filedetails/?id=568256969
http://steamcommunity.com/sharedfiles/filedetails/?id=568257078
http://steamcommunity.com/sharedfiles/filedetails/?id=568257166
http://steamcommunity.com/sharedfiles/filedetails/?id=568257318
http://steamcommunity.com/sharedfiles/filedetails/?id=568257457

**Comment by karlkarl93** [comment]
I also couldn't load the third map, Rosö, just like with Ifu, it wasn't in the editor load list.

The first map I tested was Wamako. I was expecting a Swedish environment inspired island because of the name of the map and I found out how wrong I was instantly. 
The map is a mediterranean looking island with a slightly hilly terain and very little forest cover. I tried to take screenshots of beautiful, good looking places and problems or bad looking places and I had a hard time finding the first ones. The map is very lazily made in my opinion. The best part is the biggest city, which is located in the north, I'm guessing it's the capitol. The rest of the island was very ugly to me, I disliked the combination of colours and the lack of foliage. 

Here's the album of the screenshots - http://imgur.com/a/uZOX9

The second (and last) map I tested was Sturkö. This time, I got what I was expecting, a Swedish island.
It did feel Swedish, the classical red wooden buildings are all there, and you can enter them! But you can't open the door and walk in, you have to walk through the door. Also, some of the buildings were semi see-trough.
This map was made better than Wamako in my opinion, it was nice and foresty and had nice towns and small settlements, even some suprises, but just like before, the map had a fair share of problems, like roads being weird and some custom things (like buildings and bushes) being placed badly or being broken. Also, the custom buildings had a problme that a lot of them tend to have, which is that they use low-res textures, and the houses look out of place for me.

Here's the album of the screenshots - http://imgur.com/a/IQSR0

**Comment by Fourjays** [comment]
Rejected in the meeting on 03/01/2016 due to quality concerns.
