### ISSUE TITLE
New Russian Loadouts

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#54]
Completely new Russian Loadouts.

- AK-12 instead of Izmash AK-74
- RPK-12 as AR gun
- Current Russian AR Gun to serve as Heavy Machine Gun.
- Proper structure in terms of gear regulations.
- To be completed with the additional loadouts as well.

**Comment by TheGrandVizier** [comment]
You mean Current AR Gun to serve as Medium * Machine Gun?

**Comment by adios113** [comment]
Yep, to serve as a heavier version of an Automatic Rifle, which is not static.

**Comment by adios113** [comment]
Russian Rework complete. Changes deployed to [BWI]Template_v2.vr. Requires testing by others.

**Comment by Fourjays** [comment]
We will do a test of these loadouts alongside those from #56 and #55 over the weekend.

**Comment by Fourjays** [comment]
Can issues #101 and #102 be address in these loadouts for the planned milestone?

**Comment by ShiFoo** [comment]
__Open issues:__
Rus M.Flora Backpack MTP instead of coyote
Rus loadout remove stun grenades
Rus SQL+FTL smoke nades additionally to 3GL nades
RUS RTO LR backpack -> MR3000 + MR3000 RHS
Rus MMG has 2 NVGs
Rus Pilot Programmable Radio + GPS
Rus Sniper Flora wrong uniform -> AAF Ghillie
Rus MFlora Khaki Backpack instead of blacks
Rus Flora crewman wrong vest
Rus Flora crewman olive backpack

**Comment by ShiFoo** [comment]
Changes committed to master.
